# 06 numpy.array合并与分割

In [1]:
import numpy as np

### numpy.array 的合并

In [2]:
x=np.array([1,2,3])
y=np.array([3,2,1])

In [4]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [5]:
z=np.array([666,666,666])
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [7]:
A=np.array([[1,2,3],
            [4,5,6]])
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [8]:
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [9]:
np.concatenate([A,z])

ValueError: all the input arrays must have same number of dimensions

In [10]:
np.concatenate([A,z.reshape(1,-1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [11]:
np.vstack([A,z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [13]:
B=np.full((2,2),fill_value=100)
B

array([[100, 100],
       [100, 100]])

In [14]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [15]:
C=np.full((2,3),fill_value=666)
C

array([[666, 666, 666],
       [666, 666, 666]])

In [16]:
np.vstack([A,C])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666],
       [666, 666, 666]])

### numpy.array 的分割

In [17]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.split(x,[3,7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [22]:
A=np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
np.split(A,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [27]:
np.split(A,[2],axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [28]:
np.vsplit(A,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [29]:
np.hsplit(A,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]