# 07 numpy.array 中的运算

给定一个数组，让数组中的每一个数都乘以2

In [1]:
n=10
L=[i for i in range(n)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
L*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
A=[]
for e in L :
    A.append(e*2)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [4]:
n = 1000000
L = [i for i in range(n)]

In [5]:
%%time
A=[]
for e in L:
    A.append(e*2)

Wall time: 191 ms


In [6]:
%%time
A = [2*e for e in L]

Wall time: 121 ms


In [7]:
import numpy as np
L = np.arange(n)

In [8]:
%%time
A=[2*e for e in L]

Wall time: 226 ms


In [9]:
%%time 
A=np.array([e*2 for e in L])

Wall time: 355 ms


## numpy's universal funchtions

In [11]:
X=np.arange(1,16).reshape((3,5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
X+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [13]:
X-1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
X*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [15]:
X/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [16]:
X//2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [17]:
X**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [19]:
1/X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [20]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [23]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [24]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [25]:
np.power(3,X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

## 矩阵运算

In [26]:
A=np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [28]:
B=np.full((2,2),fill_value=100)
B

array([[100, 100],
       [100, 100]])

In [30]:
A+B

array([[100, 101],
       [102, 103]])

In [31]:
A-B

array([[-100,  -99],
       [ -98,  -97]])

In [32]:
A*B

array([[  0, 100],
       [200, 300]])

In [33]:
A.dot(B)

array([[100, 100],
       [500, 500]])

In [34]:
A

array([[0, 1],
       [2, 3]])

In [35]:
A.T

array([[0, 2],
       [1, 3]])

### 向量与矩阵的运算

In [36]:
v=np.array([1,2])
v

array([1, 2])

In [41]:
A

array([[0, 1],
       [2, 3]])

In [38]:
A+v

array([[1, 3],
       [3, 5]])

In [39]:
np.vstack([v]*A.shape[0])

array([[1, 2],
       [1, 2]])

In [42]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [44]:
np.tile(v,(2,1))

array([[1, 2],
       [1, 2]])

In [45]:
np.tile(v, (2, 1)) + A

array([[1, 3],
       [3, 5]])

### 乘法

In [46]:
v

array([1, 2])

In [47]:
A

array([[0, 1],
       [2, 3]])

In [48]:
v*A

array([[0, 2],
       [2, 6]])

In [49]:
A.dot(v)

array([2, 8])

### 矩阵的逆

In [51]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [52]:
invA = np.linalg.inv(A)

In [53]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [54]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [55]:
X = np.arange(16).reshape((2, 8))

In [56]:
invX=np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

In [57]:
pinvX=np.linalg.pinv(X)

In [58]:
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -7.30583920e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [59]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.77555756e-16],
       [ 1.69309011e-15,  1.00000000e+00]])