# 05 numpy.array 基本操作

In [2]:
import numpy as np
np.random.seed(0)
x=np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
X=np.arange(15).reshape((3,5))

In [5]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## numpy.array的基本属性

In [6]:
x.ndim

1

In [7]:
X.ndim

2

In [8]:
x.shape

(10,)

In [9]:
X.shape

(3, 5)

In [10]:
x.size

10

In [11]:
X.size

15

## numpy.array 的数据访问

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[0]

0

In [14]:
x[-1]

9

In [15]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
X[0][0]

0

In [17]:
X[0,0]

0

In [18]:
X[0,3]

3

In [20]:
X[0,-1]

4

In [21]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x[0:5]

array([0, 1, 2, 3, 4])

In [23]:
x[::2]

array([0, 2, 4, 6, 8])

In [27]:
x[1::3]

array([1, 4, 7])

In [31]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [32]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [35]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [37]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [38]:
X[:,-1]

array([ 4,  9, 14])

### Subarray of numpy.array

In [41]:
subX=X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [43]:
subX[0,0]=100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [44]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [45]:
X[0,0]=0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [47]:
subX=X[:2,:3].copy()

In [48]:
subX[0,0]=100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [49]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [50]:
x.shape

(10,)

In [51]:
x.ndim

1

In [53]:
x.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
A=x.reshape((2,5))

In [56]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
B=x.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [60]:
B.ndim

2

In [62]:
B[0,0]=100
B

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9]])

In [63]:
x

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

### 大部分都是在元数据进行操作的，因此在实际的过程中需要注意使用copy（）方法