# 03 numpy.array 基础

In [1]:
import numpy

In [2]:
numpy.__version__

'1.14.3'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.14.3'

# python list 的特点

In [5]:
L=[i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[5]

5

In [7]:
L[5]=100

In [8]:
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [9]:
L[5]='Machine Learning'

In [10]:
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

In [ ]:
python的List不要求存储同样的类型，带来了效率问题。

In [15]:
import array
arr=array.array('i',[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[5]

5

In [17]:
arr[5]=100

In [18]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [19]:
arr[5]='Machine Learing'

TypeError: an integer is required (got type str)

In [20]:
arr[5]=5.

TypeError: integer argument expected, got float

array的缺点是没有将数据当做向量或者矩阵，不支持基本运算

## numpy.array

In [21]:
nparr=np.array([i for i in range(10)])

In [22]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
nparr[5]=100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [25]:
nparr[5]='Machine Learing'
nparr

ValueError: invalid literal for int() with base 10: 'Machine Learing'

In [26]:
nparr.dtype

dtype('int32')

In [27]:
nparr[5] = 5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
nparr.dtype

dtype('int32')

In [29]:
nparr[5] = 3.14
nparr

array([0, 1, 2, 3, 4, 3, 6, 7, 8, 9])