# 04 创建numpy.array

In [1]:
import numpy as np

### numpy.array

In [3]:
#np.array([list])
nparr=np.array([i for i in range(2,20,2)])
nparr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

## 其他创建np.array的方法

### zeros/ones

In [5]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones(shape=(4,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### full

In [11]:
np.full(fill_value=666,shape=(2,4))

array([[666, 666, 666, 666],
       [666, 666, 666, 666]])

### arange （这里的用法可以类比，range的用法）

In [12]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [5]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## random

In [6]:
np.random.randint(0,10)
# [0,10)之间的随机数

5

In [7]:
np.random.randint(1,10,10)

array([3, 3, 1, 9, 2, 6, 2, 4, 4, 4])

In [8]:
np.random.randint(0,1,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.random.randint(0,100,size=10)

array([61, 29, 90, 36, 36, 76, 69, 86, 57, 35])

In [11]:
np.random.randint(0,100,size=(2,4))

array([[68, 79, 30, 51],
       [73, 83, 33, 99]])

### seed

In [13]:
np.random.seed(666)

In [14]:
np.random.randint(0,10,size=(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [15]:
np.random.seed(666)
np.random.randint(0,10,size=(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

### random

In [18]:
np.random.random()

0.8578588002246146

In [19]:
np.random.random((2,4))

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197],
       [0.3497619 , 0.92389692, 0.29489453, 0.52438061]])

### normal

In [20]:
np.random.normal()

-0.25584759282610503

In [21]:
np.random.normal(0,100)

-176.43808326009957

In [26]:
x_len=10000000
x=np.arange(x_len)
y=np.random.normal(0,100,x_len)