# 04 创建numpy.array

In [2]:
import numpy as np

### numpy.array

In [3]:
#np.array([list])
nparr=np.array([i for i in range(2,20,2)])
nparr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

## 其他创建np.array的方法

### zeros/ones

In [5]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones(shape=(4,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### full

In [11]:
np.full(fill_value=666,shape=(2,4))

array([[666, 666, 666, 666],
       [666, 666, 666, 666]])

### arange （这里的用法可以类比，range的用法）

In [12]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])