# 08 numpy中的聚合操作

## sum

In [3]:
import numpy as np

L=np.random.random(100)
sum(L)

52.40793824724927

In [4]:
np.sum(L)

52.407938247249255

In [6]:
big_array=np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

## 可以看出np.sum的计算效率会更高一些

383 ms ± 137 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.02 ms ± 766 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### min,max

In [8]:
np.min(big_array)

8.100428451340846e-07

In [9]:
np.max(big_array)

0.9999973048036553

In [10]:
big_array.min()

8.100428451340846e-07

In [11]:
big_array.max()

0.9999973048036553

## 多维度聚合

In [12]:
X=np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
np.sum(X)

120

In [14]:
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [15]:
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

## 其他聚合操作

In [17]:
np.prod(X)

0

In [19]:
np.prod(X,axis=0)

array([   0,  585, 1680, 3465])

In [20]:
np.prod(X,axis=1)

array([    0,   840,  7920, 32760])

In [21]:
np.prod(X+1,axis=1)

array([   24,  1680, 11880, 43680])

In [22]:
np.mean(X)

7.5

In [23]:
np.median(X)

7.5

In [25]:
v=np.array([1,1,2,2,10])

In [26]:
v

array([ 1,  1,  2,  2, 10])

In [28]:
np.mean(v)

3.2

In [31]:
np.median(v)

2.0

In [32]:
np.percentile(big_array,q=50)

0.4997307518006617

In [33]:
np.median(big_array)

0.4997307518006617

In [34]:
np.var(big_array)

0.0832520511842658

In [36]:
np.std(big_array)

0.2885343154362507

In [37]:
x=np.random.normal(0,1,10000000)

In [38]:
np.mean(x)

-3.6298531439751e-05

In [39]:
np.std(x)

1.0000105839414917